# docker-compose.yml
services:
  database:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: backoffice
      POSTGRES_PASSWORD: backoffice
      POSTGRES_DB: backoffice
    ports:
      - "5400:5432"
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  internal:
    name: backoffice-network

volumes:
  postgres_data:
